urls.py
# -*- coding: utf-8 *-*
from django.conf.urls import url
import views

app_name = 'contable'
urlpatterns = [
    url(r'^plan_de_cuentas/(?P<ejercicio_id>\d+)/',
        views.PlanDeCuentas.as_crud(views.CuentaMixin,
                                    namespace='plan-de-cuentas')),
    url(r'^plan_de_cuentas/(?P<ejercicio_id>\d+)/copiar/$',
        views.copiar_plan_de_cuentas, name='copiar-plan-de-cuentas'),
    url(r'^plan_de_cuentas/(?P<ejercicio_id>\d+)/cierre/$',
        views.asiento_cierre, name='cierre-plan-de-cuentas'),
    url(r'^plan_de_cuentas/(?P<ejercicio_id>\d+)/apertura/$',
        views.asiento_apertura, name='apertura-plan-de-cuentas'),
    url(r'^plan_de_cuentas/(?P<ejercicio_id>\d+)/resultado/$',
        views.asiento_resultado, name='resultado-plan-de-cuentas'),
    url(r'^libro_mayor/(?P<cuenta_id>\d+)/',
        views.LibroMayor.as_view(namespace='libro-mayor')),
    url(r'^libro_diario/(?P<ejercicio_id>\d+)/',
        views.LibroDiario.as_view(namespace='libro-diario')),
    url(r'^ejercicio/',
        views.Ejercicio.as_crud(views.EjercicioMixin, namespace='ejercicio')),
    url(r'^asiento/update/(?P<asiento_id>\d+)/$',
        views.asiento_update, name="asiento-update"),
    url(r'^asiento/create/(?P<ejercicio_id>\d+)/$',
        views.asiento_create_new, name="asiento-create"),
    url(r'^asiento/delete/(?P<asiento_id>\d+)/$',
        views.asiento_delete, name="asiento-delete"),
    url(r'^asiento/resort/(?P<ejercicio_id>\d+)/$',
        views.asiento_resort, name="asiento-resort"),
    url(r'^asiento/move/(?P<asiento_id>\d+)/(?P<ejercicio_id>\d+)/$',
        views.asiento_move, name="asiento-move"),
    url(r'^plan_de_cuentas/(?P<ejercicio_id>\d+)/exportar/$',
        views.exportar_plan_de_cuentas, name='exportar-plan-de-cuentas'),
    url(r'^plan_de_cuentas/(?P<ejercicio_id>\d+)/importar/$',
        views.importar_plan_de_cuentas, name='importar-plan-de-cuentas'),
]

models.py
# -*- coding: utf-8 *-*
from django.db import models
from django.core.exceptions import ValidationError
from decimal import Decimal
from django.db.models import Sum, Count, Q
import utils
import warnings
from django.utils.deprecation import RemovedInNextVersionWarning


class Ejercicio(models.Model):
    """representa un ejercicio contable"""
    class Meta:
        # solo puede haber una cuenta por ejercicio
        permissions = (
            ("view_ejercicio", "Puede ver los ejercicios"),)

    id = models.PositiveIntegerField("Número", primary_key=True)
    fecha_inicio = models.DateField("Fecha de inicio")
    fecha_fin = models.DateField("Fecha de final")
    ano = models.PositiveIntegerField("Año")

    activo = models.BooleanField("Activo", default=False)

    def __unicode__(self):
        return str(self.ano)

    def save(self, *args, **kwargs):
        # Verifico que sea el único ejercicio activo
        e_activo = Ejercicio.objects.filter(activo=True)
        if e_activo.count() > 0:
            e_activo = e_activo[0]
        else:
            self.activo = True
            e_activo = self

        change_eactivo = False
        if self.activo is True and e_activo != self:
            e_activo.activo = False
            change_eactivo = True

        super(Ejercicio, self).save(*args, **kwargs)
        if change_eactivo:
            e_activo.save()

    def get_next_asiento_numero(self):
        """si no le asigno numero, que asigne el suiguiente"""
        asientos = self.asiento_set.order_by("-numero")
        if asientos.count() > 0:
            numero = asientos[0].numero + 1
        else:
            numero = 1

        return numero

    def resort_asiento_numero(self):
        asientos = self.asiento_set.order_by("imputacion", "numero")
        index = 1
        for asiento in asientos:
            asiento.numero = index
            asiento.save()
            index += 1

    def get_others(self):
        return Ejercicio.objects.exclude(pk=self.pk)

    def get_rel_cuentas_ids_from_codigos(self, codigos):
        ids = list()
        cuentas = self.cuenta_set.filter(codigo__in=codigos)
        for c in cuentas:
            ids += c.get_rel_ids()
        return ids

    @staticmethod
    def last():
        ejes = Ejercicio.objects.all().order_by("-ano")
        return ejes[0]

    @staticmethod
    def get_activo():
        ejs = Ejercicio.objects.order_by('-activo', '-ano')
        if ejs.count() > 0:
            if ejs[0].activo is False:
                ejs[0].activo = True
                ejs[0].save()
            return ejs[0]
        else:
            return None

    @staticmethod
    def get_ejercicio_by_date(date):
        ejs = Ejercicio.objects.filter(
            fecha_inicio__lte=date, fecha_fin__gte=date)
        if ejs.count() == 1:
            return ejs[0]
        elif ejs.count() > 1:
            raise Exception("Ejercicios superpuestos")
        else:
            return None


class CuentaKey(str):
    max_length = 13
    estruct = 5

    def __new__(cls, value):
        return str.__new__(cls, CuentaKey.NormalizeKey(value))

    def get_element(self, index):
        estructura = self.split(".")
        return int(estructura[index])

    def set_element(self, index, value):
        estructura = self.split(".")
        estructura[index] = value
        self = CuentaKey.NormalizeKey(str.join(".", estructura))

    @property
    def parent(self):
        """obtiene el codigo de la cuenta padre"""
        estructura = self.split(".")
        parent = list((0, 0, 0, 0, 0))
        parent_part = False

        for i in (4, 3, 2, 1, 0):
            e = estructura[i]
            if not parent_part:
                parent[i] = "0"
            else:
                parent[i] = e
            if e not in ("0", "00", "000"):
                parent_part = True
        return CuentaKey.NormalizeKey(str.join(".", parent))

    @staticmethod
    def check_key(key):
        """Chequea si el cógigo tiene el formato N.N.NN.NN.NNN"""
        try:
            key = CuentaKey.NormalizeKey(key)
        except (ValueError, IndexError):
            return False
        if len(key) != CuentaKey.max_length:
            return False
        estructura = key.split(".")
        if len(estructura) != CuentaKey.estruct:
            return False
        return True

    @staticmethod
    def NormalizeKey(key):
        """Toma un codigo y lo formatea (si puede) en un codigo de cuenta"""
        estructura = key.split(".")
        for i in (0, 1, 2, 3, 4):
            if i == 2 or i == 3:
                estructura[i] = str(int(estructura[i])).rjust(2, "0")
            elif i == 4:
                estructura[i] = str(int(estructura[i])).rjust(3, "0")
            else:
                estructura[i] = str(int(estructura[i]))
        return str.join(".", estructura)

    @staticmethod
    def ZeroValue():
        return CuentaKey("0.0.00.00.000")


class CuentaKeyField(models.CharField):

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = CuentaKey.max_length
        super(CuentaKeyField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        if value is None or isinstance(value, CuentaKey):
            return value

        if CuentaKey.check_key(value):
            return CuentaKey(value)
        else:
            raise ValidationError(
                "El valor no corresponde con un código de cuenta válido.")


class Cuenta(models.Model):
    """Representa una cuenta contable"""

    class Meta:
        # solo puede haber una cuenta por ejercicio
        unique_together = (('codigo', 'ejercicio'),)
        permissions = (
            ("view_plan_de_cuentas", "Puede ver los planes de cuentas"),)

    codigo = CuentaKeyField("Código")
    ejercicio = models.ForeignKey(Ejercicio)

    breve = models.CharField(
        "Acceso Rápido", max_length=5, null=True, blank=True)
    nombre = models.CharField("Nombre", max_length=127)
    imputable = models.BooleanField(default=False)

    parent = models.ForeignKey('Cuenta', null=True, blank=True)

    def save(self, *args, **kwargs):
        if isinstance(self.codigo, str):
            self.codigo = CuentaKey(self.codigo)
        parent_codigo = self.codigo.parent
        if parent_codigo != CuentaKey.ZeroValue():
            self.parent, c = Cuenta.objects.get_or_create(
                codigo=parent_codigo,
                ejercicio=self.ejercicio,
                defaults={'nombre': "(A DEFINIR)", 'imputable': False})

        super(Cuenta, self).save(*args, **kwargs)

    def get_codigo_siguiente(self):
        """obtiene el nuevo codigo de una sihguiente cuenta hija"""
        subcuentas = self.cuenta_set.order_by("-codigo")
        if subcuentas.count() > 0:
            nivel = subcuentas[0].nivel
            bloque = subcuentas[0].codigo.split(".")
            index = int(bloque[nivel])
            index += 1
            bloque[nivel] = str(index)
        else:
            bloque = self.codigo.split(".")
            bloque[self.nivel + 1] = "1"
        return CuentaKey.NormalizeKey(".".join(bloque))

    def get_saldo(self, recursive=False, fecha_fin=None, exclude=list()):
        """ retorna el saldo de la cuenta sumarizando
        los valores de los asientos
        recursive = True para profundizar la busqueda
        de saldo de manera recursiva
        fecha_fin: Hasta cierta fecha
        exclude: tipo de asiento excluidos 0,1,2,3,4
        """

        if hasattr(self, "__saldo") and not fecha_fin:
            return self.__saldo
        elif (hasattr(self, "__saldo_fecha") and
              fecha_fin in self.__saldo_fecha):
            return self.saldo_fecha[fecha_fin]
        else:
            if hasattr(self, 'debitos') and hasattr(self, 'creditos'):
                saldo = utils.PartidaDoble(self.debitos, self.creditos)
            else:

                q_filter = dict()
                q_exclude = dict()
                if fecha_fin:
                    q_filter['asiento__imputacion__lte'] = fecha_fin
                if exclude:
                    q_exclude['asiento__tipo__in'] = exclude

                asientos = self.registroasiento_set.filter(
                    **q_filter).exclude(**q_exclude)
                saldo = utils.PartidaDoble(0, 0)
                for reg in asientos:
                    saldo += reg.saldo
            if recursive:
                subcuentas = self.cuenta_set.annotate(
                    debitos=Sum("registroasiento__debe"),
                    creditos=Sum("registroasiento__haber"))

                for sc in subcuentas:
                    print sc
                    saldo = saldo + sc.get_saldo(recursive, fecha_fin, exclude)
        self.__saldo = saldo
        return saldo

    @property
    def saldo(self):
        """expone __saldo__ de manera recursiva"""
        return self.get_saldo()

    @property
    def full_saldo(self):
        """expone __saldo__ de manera recursiva de todas las cuentas"""
        return self.get_saldo(recursive=True)

    @property
    def nivel(self, recalculate=False):
        """determina el nivel de la cuenta y guarda en cache

            recalculate = True si queremos que actualize el cache
        """
        if not hasattr(self, "__nivel") or recalculate:
            self.__nivel = 4
            estructura = self.codigo.split(".")
            estructura.reverse()
            for bloque in estructura:
                if int(bloque) == 0:
                    self.__nivel -= 1
        return self.__nivel

    def get_movimientos(self):
        ids = self.get_rel_ids()
        return RegistroAsiento.objects.filter(cuenta_id__in=ids)

    def get_rel_cuentas(self):
        ids = self.get_rel_ids()
        return Cuenta.objects.filter(id__in=ids)

    _rel_ids = False

    def get_rel_ids(self, rebuild=False):
        if not self._rel_ids or rebuild:
            def make_id_list(cuenta, list):
                list.append(cuenta.id)

templates/contable/base_print.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="es">
	<head>
		
		<meta charset="utf-8" />
		<title>{{ page_title }}</title>

		<meta name="description" content="{{ page_description }}" />
		<style type="text/css">
			  @page{
			  	size:A4;
			  }

			  html, body {
				    width:100%;
				    height:100%;
				    margin: 0px;
				    padding: 0;
				    font-family: sans-serif;
    				font-size: small;
				  }
				
			  table{
			  	width:100%;
			  	border-spacing: 1px;
    			border-collapse: collapse;
    			font-size: smaller;
    			page-break-inside:avoid;
    			page-break-after:always; 
    			border: solid 1px;	
			  }


			  tr.encabezado th{
			      border: solid 1px;
			     
			  }

			  tr.transporte td{
			  	font-weight: bold;
			  }

			  div.header{
			  	height: 1.5cm;
			  	page-break-before:always; 
			  	page-break-inside:avoid;
			  	page-break-after:avoid;
			  }
			  
			  td,th{
			  	border-spacing: 1px;
			  	border: 1px;
			  	border-left: solid 1px;
			  	border-right: solid 1px;
			  }

			  td{
			  	font-size: smaller;
			  }
			  
			  tr.apertura_asiento{
			  	border-top: solid 1px;	
			  }

			 

			  td.align-right{
			  	text-align: right;
			  }
			  
			  td:nth-child(1),th:nth-child(1),
			  td:nth-child(3),th:nth-child(3),
			  td:nth-child(4),th:nth-child(4)
			  {
			  	width:100px;
			  	white-space: nowrap;
			  }

			  table tfoot{display:table-footer-group;}
			   

		</style>
	</head>

	<body>
		{% block page-content %}
		{% endblock %}
	</body>
</html>

templates/contable/datos_asiento.html
	{% for data in datalist %}
	<div class="panel">
			{{data.label}}: {{data.data}}
	</div>
	{% endfor %}

templates/contable/libro_diario_ods.html
{% load contable_extras %}<!DOCTYPE html>
<html lang="es">
	<head>
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	</head>
	<body>
		<table>
			<thead>
				<tr>
					<th width="1">Fecha</th>
					<th>Asiento</th>
					<th width="100px">Debe</th>
					<th width="100px">Haber</th>
				</tr>
			</thead>
			<tbody>
				{% if objects_list %}
				{% for asiento in objects_page %}
				<tr>
					<th class="nowrap">{{asiento.imputacion}}</th>
					<th class="align-center">
						Asiento N° {{asiento.numero}}
					</th>
					<th></th>
					<th></th>
				</tr>
				{% for reg in asiento.registroasiento_set|filter:'debe__gt=0'|order_by:'cuenta__codigo' %}
				<tr>
					<td></td>
					<td>
						{{reg.cuenta.codigo}} - {{reg.cuenta.nombre}}
					</td>
					<td class="align-right">
						{{reg.saldo.debe|hideZero|format_dinero}}
					</td>
					<td class="align-right">
					</td>
				</tr>
				{% endfor %}
				{% for reg in asiento.registroasiento_set|filter:'haber__gt=0'|order_by:'cuenta__codigo' %}
				<tr>
					<td></td>
					<td>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						{{reg.cuenta.codigo}} - {{reg.cuenta.nombre}}
					</td>
					<td class="align-right">
					</td>
					<td class="align-right">
						{{reg.saldo.haber|hideZero|format_dinero}}
					</td>
				</tr>
				{% endfor %}
				<tr>
					<td></td>
					<td>{{asiento.descripcion}}<br />
						{% if asiento.datos != "" %}
						{% datos_asiento asiento.datos %}
						{% endif %}
					</td>
					<th class="align-right"></th>
					<th class="align-right"></th>
				</tr>
				{% endfor %}
				
				{% endif %}
			</tbody>
		</table>
	</body>
</head>

templates/contable/libro_diario_print.html
{% extends "contable/base_print.html" %}
{% load contable_extras %}
{% block page-content %} 


{% for line in lines %}
	{% if forloop.first %}
		<div class="header"></div>
		<table>
			<tbody>
				{% include "contable/libro_diario_print_row.html" with tipo="encabezado" %}
				{% include "contable/libro_diario_print_row.html" with tipo="transporte" %}
	{% endif %}
				{% include "contable/libro_diario_print_row.html" %}

	{% if forloop.counter|divisibleby:73 %}
			{% include "contable/libro_diario_print_row.html" with tipo="transporte" %}
		</tbody>
	</table>
	<div class="header"></div>
	<table>
			<tbody>
				{% include "contable/libro_diario_print_row.html"  with tipo="encabezado" %}
				{% include "contable/libro_diario_print_row.html" with tipo="transporte" %}
	{% endif %}

	{% if forloop.last %}
			{% include "contable/libro_diario_print_row.html" with tipo="transporte" %}
			</tbody>
		</table>
	{% endif %}	
{% endfor %}
{% endblock %}

templates/contable/libro_diario_print_row.html
{% load contable_extras %}
{% if tipo == "encabezado" %}
<tr class="encabezado">
	<th>Fecha</th>
	<th>Cuentas</th>
	<th class="debe">Debe</th>
	<th class="haber">Haber</th>
</tr>
{% elif tipo == "transporte" %}
<tr class="transporte">
	<td></td>
	<td class="align-right">
		Transporte
	</td>
	<td class="align-right">
		{{line.5|format_dinero}}
	</td>
	<td class="align-right">
		{{line.6|format_dinero}}
	</td>
</tr>
{% elif line.4 == "asiento_numero" %}
<tr class="apertura_asiento">
	<th class="nowrap">{{line.0}}</th>
	<th class="align-center">
		Asiento N° {{line.1}}
	</th>
	<th></th>
	<th></th>
</tr>
{% elif line.4 == "registroasiento_debe" %}
<tr>
	<td></td>
	<td>
		{{line.1}}
	</td>
	<td class="align-right">
		{{line.2|hideZero|format_dinero}}
	</td>
	<td class="align-right">
	</td>
</tr>
{% elif line.4 == "registroasiento_haber" %}
<tr>
	<td></td>
	<td>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{line.1}}
	</td>
	<td class="align-right">
	</td>
	<td class="align-right">
	{{line.3|hideZero|format_dinero}}
	</td>
</tr>
{% elif line.4 == "asiento_descripcion" %}
<tr class="cierre_asiento">
	<td></td>
	<td>{{line.1}}
	</td>
	<th class="align-right"></th>
	<th class="align-right"></th>
</tr>
{% endif %}

templates/contable/libro_diario_table.html
{% load contable_extras %}
<table id="simple-table" class="table table-striped table-bordered table-hover">
	<thead>
		<tr>
			<th width="1">Fecha</th>
			<th>Asiento</th>
			<th width="100px">Debe</th>
			<th width="100px">Haber</th>
		</tr>
	</thead>
	<tbody>
		{% if objects_page %}
		{% for asiento in objects_page %}
		<tr>
			<th nowrap><a href="?fd={{asiento.imputacion|urldate}}">{{asiento.imputacion}}</a></th>
			<th class="align-center">
				{% if asiento.tipo > 0%}
				<span class="label label-success label-white middle">{{asiento.get_tipo_display}}
				</span><br/>
				{% endif %}Asiento N° {{asiento.numero}}
				{% if perms.contable.add_asiento or perms.contable.change_asiento or  perms.contable.delete_asiento  %}
				<div class="btn-group">
					<button data-toggle="dropdown" class="btn btn-success btn-minier dropdown-toggle">
					<span class="ace-icon fa fa-caret-down icon-only"></span>
					</button>
					<ul class="dropdown-menu">
						{% if perms.contable.add_asiento %}
						<li>
							<a href="{% url 'contable:asiento-create' asiento.ejercicio.pk %}">Agregar Nuevo</a>
						</li>
						{% endif %}
						{% if perms.contable.change_asiento %}
						<li>
							<a href="{% url 'contable:asiento-update' asiento.pk %}">Editar</a>
						</li>
						{% endif %}
						{% if perms.contable.delete_asiento %}
						<li>
							<a href="{% url 'contable:asiento-delete' asiento.pk %}">Eliminar</a>
						</li>
						{% endif %}
						{% if perms.contable.change_asiento %}
						<li>
							<a href="{% url 'contable:asiento-resort' asiento.ejercicio.pk %}">Reordenar Todos</a>
						</li>
						{% endif %}
						{% if perms.contable.change_asiento %}
							{% for e in ejercicio.get_others %}
							<li>
							<a href="{% url 'contable:asiento-move' asiento.pk e.pk %}">Mover al ejercicio: {{e}}</a>
							</li>
							{% endfor %}
						{% endif %}
					</ul>
				</div>
				{% endif %}
			</th>
			<th></th>
			<th></th>
		</tr>
		{% for reg in asiento.registroasiento_set|filter:'debe__gt=0'|order_by:'cuenta__codigo' %}
		<tr>
			<td></td>
			<td>
				<a href="{% url 'contable:libro-mayor:list' reg.cuenta.id %}">{{reg.cuenta.codigo}} - {{reg.cuenta.nombre}}</a>
			</td>
			<td class="align-right">
				{{reg.saldo.debe|hideZero|format_dinero}}
			</td>
			<td class="align-right">
			</td>
		</tr>
		{% endfor %}
		{% for reg in asiento.registroasiento_set|filter:'haber__gt=0'|order_by:'cuenta__codigo' %}
		<tr>
			<td></td>
			<td>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="{% url 'contable:libro-mayor:list' reg.cuenta.id %}">{{reg.cuenta.codigo}} - {{reg.cuenta.nombre}}</a>
			</td>
			<td class="align-right">
			</td>
			<td class="align-right">
				{{reg.saldo.haber|hideZero|format_dinero}}
			</td>
		</tr>
		{% endfor %}
		<tr>
			<td></td>
			<td>{{asiento.descripcion}}<br />
				{% if asiento.datos != "" %}
				{% datos_asiento asiento.datos %}
				{% endif %}
			</td>
			<th class="align-right"><div style="border-bottom: 1px solid #000;">{{asiento.saldo.debe|format_dinero }}<div></th>
			<th class="align-right"><div style="border-bottom: 1px solid #000;">{{asiento.saldo.haber|format_dinero}}<div></th>
		</tr>
		{% endfor %}
		{% else %}
		<tr>
			<td colspan="4">
					{% if ejercicio.cuenta_set.count <= 0 %}
					<div class="alert alert-danger">
						<h3>No hay plan de cuentas {{ejercicio.ano}}</h3>
						<br />
						<p>Debe configurar un <a href="{% url 'contable:plan-de-cuentas:list' ejercicio_id %}" class="btn btn-success btn-minier">Plan de Cuentas {{ejercicio.ano}}</a></p>
					</div>
					{% else %}
					<div class="alert alert-warning">
						<h3> No hay asientos en el libro </h3>
						<br />
						{% if perms.contable.add_asiento %}
							<a class="btn btn-success btn-minier" href="{% url 'contable:asiento-create' ejercicio_id %}">Agregar Primer Asiento</a>
						{% endif %}
					</div>
					{% endif %} 
			</td>
		</tr>
		{% endif %}
	</tbody>
</table>

templates/contable/plan_cuentas_export.html
[{% for c in cuentas %}{
	"codigo": "{{c.codigo}}",
	"imputable":"{{c.imputable}}", 
	"nombre": "{{c.nombre}}", 
	"breve": "{{c.breve|default:""}}"}{% if not forloop.last %},{% endif %}
{% endfor %}
]

templates/contable/plan_de_cuentas.html
{% extends "generic_views/base.html" %}
{% load staticfiles %}
{% block head_extra %}
	<script src="{% static 'generic_views/bootstrap-treeview-master/js/bootstrap-treeview.js' %}"></script>
	<script src="{% static 'generic_views/tree_view_config.js' %}"></script>	
{% endblock %}
{% block page-content %}
{% if perms.contable.add_cuenta %}
	<a class="btn btn-success btn-minier" href="{% url 'contable:plan-de-cuentas:create' ejercicio.pk %}" data-toggle="modal" data-target="#modal">Agregar Cuenta</a>
	<a class="btn btn-success btn-minier" href="{% url 'contable:copiar-plan-de-cuentas' ejercicio.pk %}" data-toggle="modal" data-target="#modal">Obtener cuentas desde otro ejercicio</a>
	<a class="btn btn-success btn-minier" href="{% url 'contable:resultado-plan-de-cuentas' ejercicio.pk %}">Crear Asiento de Resultado</a>
	<a class="btn btn-success btn-minier" href="{% url 'contable:cierre-plan-de-cuentas' ejercicio.pk %}">Crear Asiento de Cierre</a>
	<a class="btn btn-success btn-minier" href="{% url 'contable:apertura-plan-de-cuentas' ejercicio.pk %}">Crear Asiento de Apertura</a>
	<a class="btn btn-success btn-minier" href="{% url 'contable:exportar-plan-de-cuentas' ejercicio.pk %}">Exportar JSON</a>
	<a class="btn btn-success btn-minier" href="{% url 'contable:importar-plan-de-cuentas' ejercicio.pk %}" data-toggle="modal" data-target="#modal">Importar JSON</a>
{% endif %}
{% include "contable/plan_de_cuentas_table.html" %}
<div class="modal fade in" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" success="">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript" src="{% static 'generic_views/widgets_init.js' %}">
</script>
{% endblock %}

templates/contable/plan_de_cuentas_line.html
{% load contable_extras %}
<tr style="font-size:{{font_size}}px">
	<td>

		<div class="col-xs-6 col-xs-offset-{{nivel}}">
			<div class="dropdown-hover">
			{{cuenta.codigo}} - {{cuenta.nombre}}
			<ul class="dropdown-menu">
			<li><a href="{% url 'contable:libro-mayor:list' cuenta.id %}">Libro Mayor</a></li>
			{% if not cuenta.imputable %}
			<li>
				<a href="{% url 'contable:plan-de-cuentas:create' cuenta.ejercicio_id %}?parent={{cuenta.id}}" data-toggle="modal" data-target="#modal">Agregar Cuenta</a>
			</li>
			{% endif %}
			<li>
				<a href="{% url 'contable:plan-de-cuentas:update' cuenta.ejercicio_id cuenta.id %}" data-toggle="modal" data-target="#modal">Editar Cuenta</a>
			</li>
			{% if cuenta.saldo.isZero %}
			<li>
				<a href="{% url 'contable:plan-de-cuentas:delete' cuenta.ejercicio_id cuenta.id %}" data-toggle="modal" data-target="#modal">Eliminar Cuenta</a>
			</li>
			{% endif %}
			</ul>
			</div>
		</div>

	</td>
	<td class="align-right">
		{{saldo.debe|hideZero|format_dinero }}
	</td>
	<td class="align-right">
		{{saldo.haber|hideZero|format_dinero}}
	</td>
	<td class="align-right">
		{% if not saldo.isZero %}
		<span style="color:{{font_color}}">
			{{saldo.resultado|format_dinero}}
		</span>
		{% endif %}
	</td>
</tr>